[email]
host = "station.ferment.gmail.com"
port = 587
user = "fermentstation@gmail.com"
password = "Vivelekefir*"
sender = "station.ferment@gmail.com"

# plusieurs destinataires séparés par des virgules ou en liste TOML
recipients = ["chloe.etheve@supbiotech.fr", "ethevechloeemilie974@hotmail.com"]
