[email]
host = "station.ferment.gmail.com"
port = 587
user = ""
password = "lmmz ucdf nqyv avcy"
sender = "station.ferment@gmail.com"

# plusieurs destinataires séparés par des virgules ou en liste TOML
recipients = [""]
